# Generated by Django 5.1.3 on 2024-12-09 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="attachment_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Used to attach the image to another object. Cannot be used to retrieve the image file.",
                unique=True,
            ),
        ),
    ]
